/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.example;

import model.Sintoma;
import model.Diagnostico;
import function fabrica.FabricaQuestoes.answer;
import java.util.List;

query "obterDiagnosticos"
	$diagnostico : Diagnostico()
end

rule "#80 - Luz de óleo"
when
	Sintoma(evidencia == "Quais são os sintomas que o seu automóvel apresenta?",valor == "Luzes no painel");
	eval(answer("Qual é a luz que observa?", List.of("Luz de óleo","Luz do motor"), "Luz de óleo"));
then
	
end

rule "#81 - O automóvel está com o nível de óleo normal?(Sim)"
when
	Sintoma(evidencia == "Qual é a luz que observa?",valor == "Luz de óleo");
	eval(answer("1|O automóvel está com o nível de óleo normal?", List.of("Sim","Não"), "Sim"));
then

end

rule "#82 - As escovas do motor de arranque estão danificadas?(Sim)"
when
	Sintoma(evidencia == "1|O automóvel está com o nível de óleo normal?",valor == "Sim");
	eval(answer("As escovas do motor de arranque estão danificadas?", List.of("Sim","Não"), "Sim"));
then
	Diagnostico diag = new Diagnostico("Escovas do motor de arranque danificadas.");
	insert(diag);
end
//////CONSULTE UM ESPECIALISTA////// Rule 83

rule "#84 - O automóvel está com o nível de óleo normal?(Não)"
when
	Sintoma(evidencia == "Qual é a luz que observa?",valor == "Luz de óleo");
	eval(answer("1|O automóvel está com o nível de óleo normal?", List.of("Sim","Não"), "Não"));
then

end

rule "#85 - O automóvel está a pingar óleo?(Sim)"
when
	Sintoma(evidencia == "1|O automóvel está com o nível de óleo normal?",valor == "Não");
	eval(answer("O automóvel está a pingar óleo?", List.of("Sim","Não"), "Sim"));
then
	Diagnostico diag = new Diagnostico("Fuga de óleo.");
	insert(diag);
end

rule "#86 - O automóvel está a pingar óleo?(Não)"
when
	Sintoma(evidencia == "1|O automóvel está com o nível de óleo normal?",valor == "Não");
	eval(answer("O automóvel está a pingar óleo?", List.of("Sim","Não"), "Não"));
then
	Diagnostico diag = new Diagnostico("Falta de óleo.");
	insert(diag);
end

rule "#87 - Luz do motor"
when
	Sintoma(evidencia == "Quais são os sintomas que o seu automóvel apresenta?",valor == "Luzes no painel");
	eval(answer("Qual é a luz que observa?", List.of("Luz de óleo","Luz do motor"), "Luz do motor"));
then

end

rule "#88 - Qual destes sintomas o automóvel apresenta?(Ruído de chocalho)"
when
	Sintoma(evidencia == "Qual é a luz que observa?",valor == "Luz do motor");
	eval(answer("Qual destes sintomas o automóvel apresenta?", List.of("Ruído de chocalho","Problemas na ignição", "Nenhuma das anteriores"), "Ruído de chocalho"));
then

end

rule "#89 - O automóvel tem consumido mais combustível do que o habitual?(Sim)"
when
	Sintoma(evidencia == "Qual destes sintomas o automóvel apresenta?",valor == "Ruído de chocalho");
	eval(answer("1|O automóvel tem consumido mais combustível do que o habitual?", List.of("Sim","Não"), "Sim"));
then

end

rule "#90 - O automóvel tem uma perda de potência acentuada?(Sim)"
when
	Sintoma(evidencia == "1|O automóvel tem consumido mais combustível do que o habitual?",valor == "Sim");
	eval(answer("1|O automóvel tem uma perda de potência acentuada?", List.of("Sim","Não"), "Sim"));
then

end

rule "#91 - O motor morre ou há algumas falhas ao acelerar?(Sim)"
when
	Sintoma(evidencia == "1|O automóvel tem uma perda de potência acentuada?",valor == "Sim");
	eval(answer("1|O motor morre ou há algumas falhas ao acelerar?", List.of("Sim","Não"), "Sim"));
then
	Diagnostico diag = new Diagnostico("Catalisador obstruído.(100%)");
	insert(diag);
end

rule "#92 - O motor morre ou há algumas falhas ao acelerar?(Não)"
when
	Sintoma(evidencia == "1|O automóvel tem uma perda de potência acentuada?",valor == "Sim");
	eval(answer("1|O motor morre ou há algumas falhas ao acelerar?", List.of("Sim","Não"), "Não"));
then
	Diagnostico diag = new Diagnostico("Catalisador obstruído.(90%)");
	insert(diag);
end

rule "#93 - O automóvel tem uma perda de potência acentuada?(Não)"
when
	Sintoma(evidencia == "1|O automóvel tem consumido mais combustível do que o habitual?",valor == "Sim");
	eval(answer("1|O automóvel tem uma perda de potência acentuada?", List.of("Sim","Não"), "Não"));
then

end

rule "#94 - O motor morre ou há algumas falhas ao acelerar?(Sim)"
when
	Sintoma(evidencia == "1|O automóvel tem uma perda de potência acentuada?",valor == "Não");
	eval(answer("2|O motor morre ou há algumas falhas ao acelerar?", List.of("Sim","Não"), "Sim"));
then
	Diagnostico diag = new Diagnostico("Catalisador obstruído.(90%)");
	insert(diag);
end

rule "#95 - O motor morre ou há algumas falhas ao acelerar?(Não)"
when
	Sintoma(evidencia == "1|O automóvel tem uma perda de potência acentuada?",valor == "Não");
	eval(answer("2|O motor morre ou há algumas falhas ao acelerar?", List.of("Sim","Não"), "Não"));
then
	Diagnostico diag = new Diagnostico("Catalisador obstruído.(80%)");
	insert(diag);
end

rule "#96 - O automóvel tem consumido mais combustível do que o habitual?(Não)"
when
	Sintoma(evidencia == "Qual destes sintomas o automóvel apresenta?",valor == "Ruído de chocalho");
	eval(answer("1|O automóvel tem consumido mais combustível do que o habitual?", List.of("Sim","Não"), "Não"));
then

end

rule "#97 - O automóvel tem uma perda de potência acentuada?(Sim)"
when
	Sintoma(evidencia == "1|O automóvel tem consumido mais combustível do que o habitual?",valor == "Não");
	eval(answer("2|O automóvel tem uma perda de potência acentuada?", List.of("Sim","Não"), "Sim"));
then

end

rule "#98 - O motor morre ou há algumas falhas ao acelerar?(Sim)"
when
	Sintoma(evidencia == "2|O automóvel tem uma perda de potência acentuada?",valor == "Sim");
	eval(answer("3|O motor morre ou há algumas falhas ao acelerar?", List.of("Sim","Não"), "Sim"));
then
	Diagnostico diag = new Diagnostico("Catalisador obstruído.(90%)");
	insert(diag);
end

rule "#99 - O motor morre ou há algumas falhas ao acelerar?(Sim)"
when
	Sintoma(evidencia == "2|O automóvel tem uma perda de potência acentuada?",valor == "Sim");
	eval(answer("3|O motor morre ou há algumas falhas ao acelerar?", List.of("Sim","Não"), "Não"));
then
	Diagnostico diag = new Diagnostico("Catalisador obstruído.(80%)");
	insert(diag);
end

rule "#100 - O automóvel tem uma perda de potência acentuada?(Não)"
when
	Sintoma(evidencia == "1|O automóvel tem consumido mais combustível do que o habitual?",valor == "Não");
	eval(answer("2|O automóvel tem uma perda de potência acentuada?", List.of("Sim","Não"), "Não"));
then

end

rule "#101 - O motor morre ou há algumas falhas ao acelerar?(Sim)"
when
	Sintoma(evidencia == "2|O automóvel tem uma perda de potência acentuada?",valor == "Não");
	eval(answer("4|O motor morre ou há algumas falhas ao acelerar?", List.of("Sim","Não"), "Sim"));
then
	Diagnostico diag = new Diagnostico("Catalisador obstruído.(80%)");
	insert(diag);
end

rule "#102 - O motor morre ou há algumas falhas ao acelerar?(Não)"
when
	Sintoma(evidencia == "2|O automóvel tem uma perda de potência acentuada?",valor == "Não");
	eval(answer("4|O motor morre ou há algumas falhas ao acelerar?", List.of("Sim","Não"), "Não"));
then
	Diagnostico diag = new Diagnostico("Catalisador obstruído.(70%)");
	insert(diag);
end

rule "#103 - Qual destes sintomas o automóvel apresenta?(Problemas na ignição)"
when
	Sintoma(evidencia == "Qual é a luz que observa?",valor == "Luz do motor");
	eval(answer("Qual destes sintomas o automóvel apresenta?", List.of("Ruído de chocalho","Problemas na ignição", "Nenhuma das anteriores"), "Problemas na ignição"));
then

end

rule "#104 - Sente ou ouve irregularidades durante o funcionamento do motor?(Sim)"
when
	Sintoma(evidencia == "Qual destes sintomas o automóvel apresenta?",valor == "Problemas na ignição");
	eval(answer("Sente ou ouve irregularidades durante o funcionamento do motor?", List.of("Sim","Não"), "Sim"));
then

end

rule "#105 - O automóvel tem consumido mais combustível do que o habitual?(Sim)"
when
	Sintoma(evidencia == "Sente ou ouve irregularidades durante o funcionamento do motor?",valor == "Sim");
	eval(answer("2|O automóvel tem consumido mais combustível do que o habitual?", List.of("Sim","Não"), "Sim"));
then
	Diagnostico diag = new Diagnostico("Válvula EGR ou sonda lambda danificada.(100%)");
	insert(diag);
end


rule "#106 - O automóvel tem consumido mais combustível do que o habitual?(Não)"
when
	Sintoma(evidencia == "Sente ou ouve irregularidades durante o funcionamento do motor?",valor == "Sim");
	eval(answer("2|O automóvel tem consumido mais combustível do que o habitual?", List.of("Sim","Não"), "Não"));
then
	Diagnostico diag = new Diagnostico("Válvula EGR ou sonda lambda danificada.(75%)");
	insert(diag);
end

rule "#107 - Sente ou ouve irregularidades durante o funcionamento do motor?(Não)"
when
	Sintoma(evidencia == "Qual destes sintomas o automóvel apresenta?",valor == "Problemas na ignição");
	eval(answer("Sente ou ouve irregularidades durante o funcionamento do motor?", List.of("Sim","Não"), "Não"));
then

end

rule "#108 - O automóvel tem consumido mais combustível do que o habitual?(Sim)"
when
	Sintoma(evidencia == "Sente ou ouve irregularidades durante o funcionamento do motor?",valor == "Não");
	eval(answer("3|O automóvel tem consumido mais combustível do que o habitual?", List.of("Sim","Não"), "Sim"));
then
	Diagnostico diag = new Diagnostico("Válvula EGR ou sonda lambda danificada.(75%)");
	insert(diag);
end

rule "#109 - O automóvel tem consumido mais combustível do que o habitual?(Não)"
when
	Sintoma(evidencia == "Sente ou ouve irregularidades durante o funcionamento do motor?",valor == "Não");
	eval(answer("3|O automóvel tem consumido mais combustível do que o habitual?", List.of("Sim","Não"), "Não"));
then
	Diagnostico diag = new Diagnostico("Válvula EGR ou sonda lambda danificada.(50%)");
	insert(diag);
end

rule "#123 - Quais são os sintomas que o seu automóvel apresenta?(Fumo anormal)"
when
	eval(answer("Quais são os sintomas que o seu automóvel apresenta?", List.of("Fumo anormal","O veículo não consegue dar o terceiro contacto de ignição", "Luzes no painel", "?????"), "Fumo anormal"));
then

end

rule "#124 - Qual é a coloração do fumo?(Esbranquiçado)"
when
	Sintoma(evidencia == "Quais são os sintomas que o seu automóvel apresenta?",valor == "Fumo anormal");
	eval(answer("Qual é a coloração do fumo?", List.of("Esbranquiçado","Azulado", "Escura"), "Esbranquiçado"));
then
	
end

rule "#125 - O automóvel tem uma perda de potência acentuada?(Sim)"
when
	Sintoma(evidencia == "Qual é a coloração do fumo?",valor == "Esbranquiçado");
	eval(answer("3|O automóvel tem uma perda de potência acentuada?", List.of("Sim","Não"), "Sim"));
then

end

rule "#126 - O automóvel tem pouca água no reservatório?(Sim)"
when
	Sintoma(evidencia == "3|O automóvel tem uma perda de potência acentuada?",valor == "Sim");
	eval(answer("1|O automóvel tem pouca água no reservatório?", List.of("Sim","Não"), "Sim"));
then
	Diagnostico diag = new Diagnostico("Junta da cabeça queimada.(100%)");
	insert(diag);
end

rule "#127 - O automóvel tem pouca água no reservatório?(Não)"
when
	Sintoma(evidencia == "3|O automóvel tem uma perda de potência acentuada?",valor == "Sim");
	eval(answer("1|O automóvel tem pouca água no reservatório?", List.of("Sim","Não"), "Não"));
then
	Diagnostico diag = new Diagnostico("Junta da cabeça queimada.(75%)");
	insert(diag);
end

rule "#128 - O automóvel tem uma perda de potência acentuada?(Não)"
when
	Sintoma(evidencia == "Qual é a coloração do fumo?",valor == "Esbranquiçado");
	eval(answer("3|O automóvel tem uma perda de potência acentuada?", List.of("Sim","Não"), "Não"));
then

end

rule "#129 - O automóvel tem pouca água no reservatório?(Sim)"
when
	Sintoma(evidencia == "3|O automóvel tem uma perda de potência acentuada?",valor == "Não");
	eval(answer("2|O automóvel tem pouca água no reservatório?", List.of("Sim","Não"), "Sim"));
then
	Diagnostico diag = new Diagnostico("Junta da cabeça queimada.(75%)");
	insert(diag);
end

rule "#130 - O automóvel tem pouca água no reservatório?(Não)"
when
	Sintoma(evidencia == "3|O automóvel tem uma perda de potência acentuada?",valor == "Não");
	eval(answer("2|O automóvel tem pouca água no reservatório?", List.of("Sim","Não"), "Não"));
then
	Diagnostico diag = new Diagnostico("Junta da cabeça queimada.(50%)");
	insert(diag);
end

rule "#131 - Qual é a coloração do fumo?(Azulado)"
when
	Sintoma(evidencia == "Quais são os sintomas que o seu automóvel apresenta?",valor == "Fumo anormal");
	eval(answer("Qual é a coloração do fumo?", List.of("Esbranquiçado","Azulado", "Escura"), "Azulado"));
then
	
end

rule "#132 - O automóvel tem uma perda de potência acentuada?(Sim)"
when
	Sintoma(evidencia == "Qual é a coloração do fumo?",valor == "Azulado");
	eval(answer("4|O automóvel tem uma perda de potência acentuada?", List.of("Sim","Não"), "Sim"));
then

end

rule "#133 - O automóvel está com o nível de óleo normal?(Não)"
when
	Sintoma(evidencia == "4|O automóvel tem uma perda de potência acentuada?",valor == "Sim");
	eval(answer("2|O automóvel está com o nível de óleo normal?", List.of("Sim","Não"), "Não"));
then
	Diagnostico diag = new Diagnostico("Desgaste dos segmentos (100%)");
	insert(diag);
end

rule "#134 - O automóvel está com o nível de óleo normal?(Sim)"
when
	Sintoma(evidencia == "4|O automóvel tem uma perda de potência acentuada?",valor == "Sim");
	eval(answer("2|O automóvel está com o nível de óleo normal?", List.of("Sim","Não"), "Sim"));
then
	Diagnostico diag = new Diagnostico("Desgaste dos segmentos (75%)");
	insert(diag);
end

rule "#135 - O automóvel tem uma perda de potência acentuada?(Não)"
when
	Sintoma(evidencia == "Qual é a coloração do fumo?",valor == "Azulado");
	eval(answer("4|O automóvel tem uma perda de potência acentuada?", List.of("Sim","Não"), "Não"));
then

end

rule "#136 - O automóvel está com o nível de óleo normal?(Não)"
when
	Sintoma(evidencia == "4|O automóvel tem uma perda de potência acentuada?",valor == "Não");
	eval(answer("3|O automóvel está com o nível de óleo normal?", List.of("Sim","Não"), "Não"));
then
	Diagnostico diag = new Diagnostico("Desgaste dos segmentos (75%)");
	insert(diag);
end

rule "#137 - O automóvel está com o nível de óleo normal?(Sim)"
when
	Sintoma(evidencia == "4|O automóvel tem uma perda de potência acentuada?",valor == "Não");
	eval(answer("3|O automóvel está com o nível de óleo normal?", List.of("Sim","Não"), "Sim"));
then
	Diagnostico diag = new Diagnostico("Desgaste dos segmentos (50%)");
	insert(diag);
end